const GET = 'get';
const GETS = 'gets';
const SET = 'set';
const ADD = 'add';
const REPLACE = 'replace';
const APPEND = 'append';
const PREPREND = 'prepend';
const CAS = 'cas';
const COMMANDS_NAMES = [GET, GETS, SET, ADD, REPLACE, APPEND, PREPREND, CAS];
const RETRIEVAL_COMMANDS = [GET, GETS];
const COMMAND_CAS_LENGTH = 6;
const COMMANDS_ADD_LENGTH = 5;
const COMMANDS_GET_LENGTH = 1;
const MAX_VALUES_UNSIGNED_16BIT = 65535;
const COMMAND_NOT_FOUND = 'ERROR';
const STORED = 'STORED';
const END = 'END';
const EXISTS = 'EXISTS';
const NOT_FOUND = 'NOT_FOUND';
const NOT_STORED = 'NOT_STORED';
const CLIENT_ERROR = 'CLIENT_ERROR';
const BAD_COMMAND_LINE_FORMAT = `${CLIENT_ERROR} bad command line format`;
const BAD_DATA_CHUNK = `${CLIENT_ERROR} bad data chunk`;
const LINE_BREAK = '\r\n';

module.exports = {
  GET,
  GETS,
  SET,
  ADD,
  REPLACE,
  APPEND,
  PREPREND,
  CAS,
  COMMAND_NOT_FOUND,
  NOT_STORED,
  NOT_FOUND,
  STORED,
  END,
  EXISTS,
  COMMANDS_NAMES,
  RETRIEVAL_COMMANDS,
  COMMAND_CAS_LENGTH,
  BAD_COMMAND_LINE_FORMAT,
  LINE_BREAK,
  BAD_DATA_CHUNK,
  COMMANDS_ADD_LENGTH,
  COMMANDS_GET_LENGTH,
  MAX_VALUES_UNSIGNED_16BIT
};
