const COMMAND_CAS_LENGTH = 6;
const COMMANDS_ADD_LENGTH = 5;
const COMMANDS_GET_LENGTH = 1;
const MAX_VALUES_UNSIGNED_16BIT = 65535;

module.exports = {
  COMMAND_CAS_LENGTH,
  COMMANDS_ADD_LENGTH,
  COMMANDS_GET_LENGTH,
  MAX_VALUES_UNSIGNED_16BIT
};
